version: '3.7' # Define the Docker Compose file format version

services:
  mysql:
    image: mysql
    container_name: mysql-blog-maven
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: blog_db
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
